[env:blackpill_f411ce]
platform = ststm32
board = genericSTM32F411CE
framework = arduino
monitor_speed = 115200
lib_deps =
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
build_flags = -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
